apiVersion: v1
kind: Secret
metadata:
  name: payment-api-secrets
type: Opaque
stringData:
  connectionString: "Server=sqlserver;Database=fcg;User Id=sa;Password=Olszewski@123;TrustServerCertificate=True"
  paymentDefaultApiKey: "ak_ewr4dsWehiwAT"
  paymentDefaultEncryptionKey: "ek_SweRsdFas4uT5"
  rabbitMQDefaultUser: "admin"
  rabbitMQDefaultPass: admin123
  rabbitMQDefaultVHost: "/"
  rabbitMQDefaultHost: "rabbitmq"
