apiVersion: v1
kind: Secret
metadata:
  name: notification-api-secrets
type: Opaque
stringData:
  rabbitMQDefaultUser: "admin"
  rabbitMQDefaultPass: admin123
  rabbitMQDefaultVHost: "/"
  rabbitMQDefaultHost: "rabbitmq"
