apiVersion: v1
kind: Secret
metadata:
  name: common-secrets
type: Opaque
stringData:
  saPassword: "Olszewski@123"
  rabbitMQDefaultUser: "admin"
  rabbitMQDefaultPass: admin123
  rabbitMQDefaultVHost: "/"
  rabbitMQDefaultHost: "rabbitmq"
