apiVersion: v1
kind: Secret
metadata:
  name: catalog-api-secrets
type: Opaque
stringData:
  connectionString: "Server=sqlserver;Database=fcg;User Id=sa;Password=Olszewski@123;TrustServerCertificate=True"
  jwtKey: "32nklfdsknsdknf332032505702da5ff3179e1safasfdsfbajwqob0087cf0cfdd1c72352390ujrfsdoklmfgdkdsnla"
  rabbitMQDefaultUser: "admin"
  rabbitMQDefaultPass: admin123
  rabbitMQDefaultVHost: "/"
  rabbitMQDefaultHost: "rabbitmq"
